services:
  traefik:
    image: traefik:v3.1  # Using stable v3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      # Define Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Enable File Provider for non-docker services
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"     # Standard HTTPS port
      - "8081:8080"   # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic:/etc/traefik/dynamic  # Mount the whole folder
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows Traefik to talk to your PC
